jobs:
  build_and_test:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Set timeout to 30 minutes for the entire job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up PyPy 3.7
        run: |
          sudo apt-get update
          sudo apt-get install -y pypy3  # Install PyPy 3.7

      - name: Install dependencies
        run: |
          pypy3 -m ensurepip  # Ensure pip is installed for PyPy
          pypy3 -m pip install --upgrade pip
          pypy3 -m pip install -r requirements.txt  # Install from requirements.txt

      - name: Ensure RAGNAROK is executable
        run: |
          test -f RAGNAROK && chmod +x RAGNAROK || echo "RAGNAROK file not found, skipping chmod"
      
      - name: Run tests
        run: |
          pypy3 rag.py  # Run the tests using PyPy
